// <auto-generated />
using System;
using System.Collections.Generic;
using HilmaAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HilmaAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HilmaDbContext))]
    [Migration("20260804092242_NoticeChunks")]
    partial class NoticeChunks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HilmaAgent.Core.Ingestion.IngestionCheckpoint", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSeenPublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Source");

                    b.ToTable("IngestionCheckpoints");
                });

            modelBuilder.Entity("HilmaAgent.Core.Notices.Notice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BuyerNationalRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BuyerOrganizationType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<List<string>>("CpvCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("EFormsXml")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EstimatedValueMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EstimatedValueMin")
                        .HasColumnType("numeric");

                    b.Property<bool>("EstimatedValueWithheld")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("NoticeType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("NoticeTypeCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("Region")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("SubmissionDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CpvCodes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CpvCodes"), "gin");

                    b.HasIndex("PublicationDate");

                    b.HasIndex("Region");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Region"), "gin");

                    b.HasIndex("Source");

                    b.HasIndex("SubmissionDeadline");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("HilmaAgent.Core.Notices.NoticeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LotId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NoticeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("VectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddingModel");

                    b.HasIndex("NoticeId");

                    b.ToTable("NoticeChunks");
                });

            modelBuilder.Entity("HilmaAgent.Core.Notices.NoticeChunk", b =>
                {
                    b.HasOne("HilmaAgent.Core.Notices.Notice", "Notice")
                        .WithMany()
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");
                });
#pragma warning restore 612, 618
        }
    }
}
