// <auto-generated />
using System;
using System.Collections.Generic;
using HilmaAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HilmaAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HilmaDbContext))]
    partial class HilmaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HilmaAgent.Core.Ingestion.IngestionCheckpoint", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("LastSeenPublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Source");

                    b.ToTable("IngestionCheckpoints");
                });

            modelBuilder.Entity("HilmaAgent.Core.Notices.Notice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("BuyerNationalRegistrationNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BuyerOrganizationType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<List<string>>("CpvCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Currency")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("EFormsXml")
                        .HasColumnType("text");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EstimatedValueMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("EstimatedValueMin")
                        .HasColumnType("numeric");

                    b.Property<bool>("EstimatedValueWithheld")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("NoticeType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("NoticeTypeCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<List<string>>("Region")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("SubmissionDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("CpvCodes");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CpvCodes"), "gin");

                    b.HasIndex("PublicationDate");

                    b.HasIndex("Region");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Region"), "gin");

                    b.HasIndex("Source");

                    b.HasIndex("SubmissionDeadline");

                    b.ToTable("Notices");
                });
#pragma warning restore 612, 618
        }
    }
}
